### ISSUE TITLE
Fay 控制器已经生成音频结果，照片虚拟人项目中也获取到音频，但是无法播放声音

### ISSUE THREAD

**Issue by dm521** [waityousea/xuniren#7]
我在Windows 11 下面， pytorch 1.12.1， cuda 11.3， pytorch3d 0.7.1 环境下，所有的组件也已经成功安装。执行命令的时候， 出现下面的结果。

![VLT67EWSROOG1YL OAX9UE8](https://github.com/waityousea/xuniren/assets/12683955/d5f4d659-c336-41f7-94c1-1e20a03fdf3d)

能否告知，哪里有问题了？

**Comment by evolutionjay** [comment]
我看不懂文档。。。搞了半天都不知道怎么做，是我的理解能力出了问题吗？

**Comment by HongdaChen** [comment]
> 我看不懂文档。。。搞了半天都不知道怎么做，是我的理解能力出了问题吗？

看不懂就对了，付费进群吧

**Comment by xxm1668** [comment]
故意留的bug,然后付费解决嘛
